from .session_processor import SessionProcessor
from .frames_file_processor import FramesFileProcessor
from .motioncor2_processor import Motioncor2Processor
from .ctffind_processor import CtffindProcessor