#!/bin/bash
function cleanup {
	conda deactivate
}
trap cleanup EXIT

SCRIPT_DIR=$(dirname $(realpath $0))

if [ -z "$1" ]; then
    ENV_FILE="${SCRIPT_DIR}/hotspur_env.sh"
else
    ENV_FILE="$1"
fi

source "$ENV_FILE"

source activate "$HOTSPUR_CONDA_ENV"

python3 "${SCRIPT_DIR}/collection_processor.py" $@

cleanup
