#!/eppec/storage/sw/cky-tools/site/bin/python
from sqlitedict import SqliteDict
import sys
import pystar2
import numpy as np

def load(path):
    return list(pystar2.load(path)[''].values())[0]

def save(particles, orig, path):
    keys = orig.dtype.names
    pystar2.save( { '': {keys: particles } }, path)

mydict = SqliteDict(sys.argv[1])

list_good = []
star_data = 0
star_data_list=[]
for key in mydict:
    if "tag" in mydict[key] and mydict[key]["tag"] == "good":
        list_good.append(key)


for key in list_good:
    if star_data == 0:
        print(key)
        print(key+"_mc_DW_gctf.star")
        star_data = load(key+"_mc_DW_gctf.star")
        star_data_list.append(star_data[0])
    else:
        print(key)
        star_data_list.append(load(key+"_mc_DW_gctf.star")[0])

save(star_data_list, star_data, sys.argv[2])
