#!/bin/bash

CONDA_ENV=/home/users/gingerid/.conda/envs/hotspur2

function cleanup {
	conda deactivate
}
trap cleanup EXIT

source ./hotspur_env.sh

source activate "$CONDA_ENV"
python3 ./collection_processor.py $@
cleanup
