#!/bin/bash


CONDA_ENV="hotspur-pncc"
SCRIPT_DIR=$(dirname $(realpath $0))
CONFIG_FILE="${SCRIPT_DIR}/setup/hotspur-config.yml"
EXE="${SCRIPT_DIR}/hotspur.py"


main()
{
	# https://github.com/conda/conda/issues/7980
	eval "$(conda shell.bash hook)"
	conda activate "$CONDA_ENV"
	trap cleanup EXIT

	python3 "$EXE" "$CONFIG_FILE" ${@}

	cleanup
}

cleanup()
{
	conda deactivate
}

main ${@}
