export HOTSPUR_PATH="/pncc/storage/1/processing/hotspur"
export HOTSPUR_SEARCH_GLOBS="/pncc/storage/1/rawdata/pncc/*/*/*/frames/"
export HOTSPUR_ADMIN_NAME="pncc"
export HOTSPUR_ADMIN_PASS="cryoem"
export HOTSPUR_HASH_SALT="feilivinglab-17"
export HOTSPUR_GPUS="0,1,2,3"
export HOTSPUR_THREADS="12"
export HOTSPUR_SESSION_MAX_AGE="7"