app:
- name: "hotspur"
- data_path: "/hotspur"

processing:
  conda_env: "~/.conda/envs/hotspur"
  globs:
  - "/pncc/storage/1/rawdata/pncc/*/*/*/frames/"
  hash_salt: "hotspur"
  gpus: [0,1,2,3]
  threads: 12
  session_max_age: 7 

network:
  domain: "loki.ohsu.edu"
  port: "80"

couchdb:
  admin_name: "admin"
  admin_pass: "password"
  data_path: "/hotspur/couchdb"