version: '3'
services:
  couchdb:
    image: "hotspur/couchdb"
    container_name: {app[name]}-couchdb
    volumes:
      - {app[data_path]}/couchdb:/opt/couchdb/data
    ports:
      - "5984"
    environment:
      - COUCHDB_USER={couchdb[admin_name]}
      - COUCHDB_PASSWORD={couchdb[admin_pass]}

  fileserver:
    image: hotspur/web-fileserver
    container_name: {app[name]}-web-fileserver
    volumes:
      - {app[data_path]}/hashed:/hotspur
    ports:
      - "80"

  view:
    depends_on:
      - couchdb
      - fileserver
    image: hotspur/web-view
    container_name: {app[name]}-web-view
    ports:
      - "80"

  router:
    depends_on:
      - couchdb
      - fileserver
      - view
    image: hotspur/web-router
    container_name: {app[name]}-web-router
    ports:
      - "80:{network[port]}"