version: '3'
services:
  couchdb:
    image: hotspur/couchdb
    container_name: {app_name}-couchdb
    volumes:
      - {data_path}couchdb:/opt/couchdb/data
    expose:
      - "5984"
    environment:
      - COUCHDB_USER={admin_name}
      - COUCHDB_PASSWORD={admin_pass}

  fileserver:
    image: hotspur/web-fileserver
    container_name: {app_name}-web-fileserver
    volumes:
      - {data_path}sessions:/hotspur
    expose:
      - "80"

  view:
    depends_on:
      - couchdb
      - fileserver
    image: hotspur/web-view
    container_name: {app_name}-web-view
    expose:
      - "80"

  router:
    depends_on:
      - couchdb
      - fileserver
      - view
    image: hotspur/web-router
    container_name: {app_name}-web-router
    ports:
      - "{port}:80"
    environment:
      - HOTSPUR_HOST={host}
      - HOTSPUR_PORT={port}
      - HOTSPUR_APP_NAME={app_name}