name: hotspur
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - certifi=2019.3.9
  - dbus=1.13.6
  - expat=2.2.5
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - giflib=5.1.9
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=58.2
  - jasper=1.900.1
  - jpeg=9c
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.28.0
  - lz4-c=1.8.3
  - ncurses=6.1
  - nettle=3.4.1
  - numba=0.43.1
  - numpy=1.16.4
  - openblas=0.3.6
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1b
  - pcre=8.41
  - pip=19.1.1
  - pixman=0.34.0
  - pthread-stubs=0.4
  - pyfftw=0.11.1
  - python=3.7.3
  - python-couchdb=1.2
  - pyyaml=5.1.1
  - qt=5.9.7
  - readline=7.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - tifffile=0.15.1
  - tk=8.6.9
  - wheel=0.33.4
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.4.0

