#!/bin/bash

set -e

YML=environment.yml

if [ -e "$YML" ]; then
    echo "File already exists. Making a backup before overwriting."
    now=$(date +"%Y-%m-%d_%T")
    backup="${YML}.${now}.bak"
    mv "$YML" "$backup"
    echo "Created ${backup}"
fi

conda env export --no-builds | grep -v "^prefix: " > "$YML"
echo "Saved ${YML}"
